apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: hackathon-k3d
servers: 1
agents: 0
kubeAPI:
  host: 127.0.0.1
ports:
  - port: "80:80"
    nodeFilters:
      - loadbalancer
  - port: "443:443"
    nodeFilters:
      - loadbalancer
options:
  kubeconfig:
    updateDefaultKubeconfig: true
