apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: prd
  labels:
    app.kubernetes.io/name: getting-started
    app.kubernetes.io/instance: app
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: getting-started
      app.kubernetes.io/instance: app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: getting-started
        app.kubernetes.io/instance: app
    spec:
      containers:
        - name: app
          image: ${IMAGE}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /q/health/ready
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /q/health/live
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          securityContext:
            runAsNonRoot: true
            runAsUser: 10001
            capabilities:
              drop:
                - ALL
            allowPrivilegeEscalation: false
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
