apiVersion: v1
kind: Service
metadata:
  name: app
  namespace: ${NAMESPACE}
  labels:
    app.kubernetes.io/name: getting-started
    app.kubernetes.io/instance: app
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: getting-started
    app.kubernetes.io/instance: app
