name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  packages: write
  security-events: write

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

env:
  IMAGE: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:${{ github.sha }}

jobs:
  build:
    name: build-test-scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: java

      - name: Build and test (Maven)
        run: mvn -B -DskipTests=false package

      - name: Upload JUnit reports
        uses: actions/upload-artifact@v4
        with:
          name: junit-reports
          path: target/surefire-reports/*.xml

      - name: Run CodeQL analysis
        uses: github/codeql-action/analyze@v2

      - name: Build container image (local, no push)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          load: true
          tags: ${{ env.IMAGE }}
          push: false

      - name: Trivy scan (fail on HIGH/CRITICAL)
        run: |
          docker run --rm -v /var/run/docker.sock:/var/run/docker.sock aquasecurity/trivy:0.41.2 image --exit-code 1 --severity HIGH,CRITICAL $IMAGE || (echo "Trivy found HIGH/CRITICAL vulnerabilities" && exit 1)

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push image to GHCR
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE }}
            ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:des
        
      - name: Upload build metadata
        uses: actions/upload-artifact@v4
        with:
          name: image-metadata
          path: |
            target/quarkus-app/application.properties
            quarkus-artifact.properties
