name: CI

on:
  push:
    branches: [ main ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  security-events: write

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

env:
  IMAGE_REPO: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}

jobs:
  build:
    name: build-test-scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      # Temporarily disabled due to SARIF upload permission issues
      # - name: Initialize CodeQL
      #   uses: github/codeql-action/init@v3
      #   with:
      #     languages: java

      - name: Build and test (Maven)
        run: mvn -B -DskipTests=false package

      - name: Upload JUnit reports
        uses: actions/upload-artifact@v4
        with:
          name: junit-reports
          path: target/surefire-reports/*.xml

      # Temporarily disabled due to SARIF upload permission issues
      # - name: Run CodeQL analysis
      #   uses: github/codeql-action/analyze@v3

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_REPO }}
          tags: |
            type=raw,value=${{ github.sha }}
            type=ref,event=tag

      - name: Build container image (local, no push)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          load: true
          tags: ${{ steps.meta.outputs.tags }}
          push: false

      - name: Trivy scan (fail on HIGH/CRITICAL)
        uses: aquasecurity/trivy-action@0.32.0
        with:
          scan-type: image
          image-ref: ${{ env.IMAGE_REPO }}:${{ github.sha }}
          format: table
          severity: HIGH,CRITICAL
          exit-code: '1'

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push image to GHCR
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
        
      - name: Upload build metadata
        uses: actions/upload-artifact@v4
        with:
          name: image-metadata
          if-no-files-found: error
          path: |
            target/classes/application.properties
            target/quarkus-artifact.properties
